-- Схема БД Filmorate. Spring выполняет этот файл при каждом старте (spring.sql.init.mode=always),
-- поэтому таблицы создаются через IF NOT EXISTS.

-- Возрастные рейтинги MPA. id не генерируется: значения фиксированы (1-5) и приходят из data.sql.
CREATE TABLE IF NOT EXISTS mpa (
    id    INTEGER      PRIMARY KEY,
    name  VARCHAR(50)  NOT NULL
);

-- Жанры. id не генерируется: значения фиксированы (1-6) и приходят из data.sql.
CREATE TABLE IF NOT EXISTS genres (
    id    INTEGER      PRIMARY KEY,
    name  VARCHAR(50)  NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255)  NOT NULL,
    login     VARCHAR(255)  NOT NULL,
    name      VARCHAR(255)  NOT NULL,
    birthday  DATE          NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id            BIGINT                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)                NOT NULL,
    description   VARCHAR(200),
    release_date  DATE                        NOT NULL,
    duration      INTEGER                     NOT NULL,
    -- без NOT NULL: API допускает фильм без рейтинга
    mpa_id        INTEGER REFERENCES mpa(id)
);

-- Связь «фильм — жанр», многие ко многим.
-- Составной первичный ключ не даёт записать один и тот же жанр фильму дважды.
CREATE TABLE IF NOT EXISTS film_genres (
    film_id    BIGINT   NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    genre_id   INTEGER  NOT NULL REFERENCES genres(id),
    PRIMARY KEY (film_id, genre_id)
);

-- Лайки: строка означает, что пользователь отметил фильм. Повторный лайк не пройдёт по первичному ключу.
CREATE TABLE IF NOT EXISTS film_likes (
    film_id    BIGINT   NOT NULL REFERENCES films(id)  ON DELETE CASCADE,
    user_id    BIGINT   NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

-- Дружба односторонняя: строка означает, что user_id добавил friend_id.
-- Взаимная дружба — две строки.
CREATE TABLE IF NOT EXISTS friendship (
    user_id    BIGINT   NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    friend_id  BIGINT   NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);